//
// OryBatchPatchIdentitiesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Patch identities response */
public struct OryBatchPatchIdentitiesResponse: Sendable, Codable, ParameterConvertible, Hashable {

    /** The patch responses for the individual identities. */
    public var identities: [OryIdentityPatchResponse]?

    public init(identities: [OryIdentityPatchResponse]? = nil) {
        self.identities = identities
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case identities
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(identities, forKey: .identities)
    }
}

