//
// OryContinueWithVerificationUi.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Indicates, that the UI flow could be continued by showing a verification ui */
public struct OryContinueWithVerificationUi: Sendable, Codable, ParameterConvertible, Hashable {

    public enum OryAction: String, Sendable, Codable, CaseIterable {
        case showVerificationUi = "show_verification_ui"
    }
    /** Action will always be `show_verification_ui` show_verification_ui ContinueWithActionShowVerificationUIString */
    public var action: OryAction
    public var flow: OryContinueWithVerificationUiFlow

    public init(action: OryAction, flow: OryContinueWithVerificationUiFlow) {
        self.action = action
        self.flow = flow
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case action
        case flow
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(action, forKey: .action)
        try container.encode(flow, forKey: .flow)
    }
}

