//
// OryCourierMessageType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** It can either be &#x60;email&#x60; or &#x60;phone&#x60; */
public enum OryCourierMessageType: String, Sendable, Codable, CaseIterable {
    case email = "email"
    case phone = "phone"
}
