//
// OryContinueWithRecoveryUi.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Indicates, that the UI flow could be continued by showing a recovery ui */
public struct OryContinueWithRecoveryUi: Sendable, Codable, ParameterConvertible, Hashable {

    public enum OryAction: String, Sendable, Codable, CaseIterable {
        case showRecoveryUi = "show_recovery_ui"
    }
    /** Action will always be `show_recovery_ui` show_recovery_ui ContinueWithActionShowRecoveryUIString */
    public var action: OryAction
    public var flow: OryContinueWithRecoveryUiFlow

    public init(action: OryAction, flow: OryContinueWithRecoveryUiFlow) {
        self.action = action
        self.flow = flow
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case action
        case flow
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(action, forKey: .action)
        try container.encode(flow, forKey: .flow)
    }
}

