//
// OryContinueWithSettingsUi.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Indicates, that the UI flow could be continued by showing a settings ui */
public struct OryContinueWithSettingsUi: Sendable, Codable, ParameterConvertible, Hashable {

    public enum OryAction: String, Sendable, Codable, CaseIterable {
        case showSettingsUi = "show_settings_ui"
    }
    /** Action will always be `show_settings_ui` show_settings_ui ContinueWithActionShowSettingsUIString */
    public var action: OryAction
    public var flow: OryContinueWithSettingsUiFlow

    public init(action: OryAction, flow: OryContinueWithSettingsUiFlow) {
        self.action = action
        self.flow = flow
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case action
        case flow
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(action, forKey: .action)
        try container.encode(flow, forKey: .flow)
    }
}

