//
// OryErrorAuthenticatorAssuranceLevelNotSatisfied.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OryErrorAuthenticatorAssuranceLevelNotSatisfied: Sendable, Codable, ParameterConvertible, Hashable {

    public var error: OryGenericError?
    /** Points to where to redirect the user to next. */
    public var redirectBrowserTo: String?

    public init(error: OryGenericError? = nil, redirectBrowserTo: String? = nil) {
        self.error = error
        self.redirectBrowserTo = redirectBrowserTo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case error
        case redirectBrowserTo = "redirect_browser_to"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(error, forKey: .error)
        try container.encodeIfPresent(redirectBrowserTo, forKey: .redirectBrowserTo)
    }
}

