//
// OryErrorFlowReplaced.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Is sent when a flow is replaced by a different flow of the same class */
public struct OryErrorFlowReplaced: Sendable, Codable, ParameterConvertible, Hashable {

    public var error: OryGenericError?
    /** The flow ID that should be used for the new flow as it contains the correct messages. */
    public var useFlowId: String?

    public init(error: OryGenericError? = nil, useFlowId: String? = nil) {
        self.error = error
        self.useFlowId = useFlowId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case error
        case useFlowId = "use_flow_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(error, forKey: .error)
        try container.encodeIfPresent(useFlowId, forKey: .useFlowId)
    }
}

