//
// OryErrorGeneric.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The standard Ory JSON API error format. */
public struct OryErrorGeneric: Sendable, Codable, ParameterConvertible, Hashable {

    public var error: OryGenericError

    public init(error: OryGenericError) {
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(error, forKey: .error)
    }
}

