//
// OryIdentityWithCredentialsOidcConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OryIdentityWithCredentialsOidcConfig: Sendable, Codable, ParameterConvertible, Hashable {

    public var config: OryIdentityWithCredentialsPasswordConfig?
    /** A list of OpenID Connect Providers */
    public var providers: [OryIdentityWithCredentialsOidcConfigProvider]?

    public init(config: OryIdentityWithCredentialsPasswordConfig? = nil, providers: [OryIdentityWithCredentialsOidcConfigProvider]? = nil) {
        self.config = config
        self.providers = providers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case config
        case providers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(config, forKey: .config)
        try container.encodeIfPresent(providers, forKey: .providers)
    }
}

