//
// OryIdentityCredentialsOidc.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OryIdentityCredentialsOidc: Sendable, Codable, ParameterConvertible, Hashable {

    public var providers: [OryIdentityCredentialsOidcProvider]?

    public init(providers: [OryIdentityCredentialsOidcProvider]? = nil) {
        self.providers = providers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case providers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(providers, forKey: .providers)
    }
}

