//
// OryIdentitySchemaContainer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** An Identity JSON Schema Container */
public struct OryIdentitySchemaContainer: Sendable, Codable, ParameterConvertible, Hashable {

    /** The ID of the Identity JSON Schema */
    public var id: String?
    /** The actual Identity JSON Schema */
    public var schema: JSONValue?

    public init(id: String? = nil, schema: JSONValue? = nil) {
        self.id = id
        self.schema = schema
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case schema
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(schema, forKey: .schema)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension OryIdentitySchemaContainer: Identifiable {}
