//
// OryIdentityWithCredentials.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Create Identity and Import Credentials */
public struct OryIdentityWithCredentials: Sendable, Codable, ParameterConvertible, Hashable {

    public var oidc: OryIdentityWithCredentialsOidc?
    public var password: OryIdentityWithCredentialsPassword?

    public init(oidc: OryIdentityWithCredentialsOidc? = nil, password: OryIdentityWithCredentialsPassword? = nil) {
        self.oidc = oidc
        self.password = password
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case oidc
        case password
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(oidc, forKey: .oidc)
        try container.encodeIfPresent(password, forKey: .password)
    }
}

