//
// OryIdentityPatch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Payload for patching an identity */
public struct OryIdentityPatch: Sendable, Codable, ParameterConvertible, Hashable {

    public var create: OryCreateIdentityBody?
    /** The ID of this patch.  The patch ID is optional. If specified, the ID will be returned in the response, so consumers of this API can correlate the response with the patch. */
    public var patchId: String?

    public init(create: OryCreateIdentityBody? = nil, patchId: String? = nil) {
        self.create = create
        self.patchId = patchId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case create
        case patchId = "patch_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(create, forKey: .create)
        try container.encodeIfPresent(patchId, forKey: .patchId)
    }
}

