//
// OryPatchIdentitiesBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Patch Identities Body */
public struct OryPatchIdentitiesBody: Sendable, Codable, ParameterConvertible, Hashable {

    /** Identities holds the list of patches to apply  required */
    public var identities: [OryIdentityPatch]?

    public init(identities: [OryIdentityPatch]? = nil) {
        self.identities = identities
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case identities
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(identities, forKey: .identities)
    }
}

