//
// OryUiNode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Nodes are represented as HTML elements or their native UI equivalents. For example, a node can be an &#x60;&lt;img&gt;&#x60; tag, or an &#x60;&lt;input element&gt;&#x60; but also &#x60;some plain text&#x60;. */
public struct OryUiNode: Sendable, Codable, ParameterConvertible, Hashable {

    public enum OryGroup: String, Sendable, Codable, CaseIterable {
        case _default = "default"
        case password = "password"
        case oidc = "oidc"
        case profile = "profile"
        case link = "link"
        case code = "code"
        case totp = "totp"
        case lookupSecret = "lookup_secret"
        case webauthn = "webauthn"
        case passkey = "passkey"
        case identifierFirst = "identifier_first"
    }
    public enum OryType: String, Sendable, Codable, CaseIterable {
        case text = "text"
        case input = "input"
        case img = "img"
        case a = "a"
        case script = "script"
    }
    public var attributes: OryUiNodeAttributes
    /** Group specifies which group (e.g. password authenticator) this node belongs to. default DefaultGroup password PasswordGroup oidc OpenIDConnectGroup profile ProfileGroup link LinkGroup code CodeGroup totp TOTPGroup lookup_secret LookupGroup webauthn WebAuthnGroup passkey PasskeyGroup identifier_first IdentifierFirstGroup */
    public var group: OryGroup
    public var messages: [OryUiText]
    public var meta: OryUiNodeMeta
    /** The node's type text Text input Input img Image a Anchor script Script */
    public var type: OryType

    public init(attributes: OryUiNodeAttributes, group: OryGroup, messages: [OryUiText], meta: OryUiNodeMeta, type: OryType) {
        self.attributes = attributes
        self.group = group
        self.messages = messages
        self.meta = meta
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attributes
        case group
        case messages
        case meta
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(attributes, forKey: .attributes)
        try container.encode(group, forKey: .group)
        try container.encode(messages, forKey: .messages)
        try container.encode(meta, forKey: .meta)
        try container.encode(type, forKey: .type)
    }
}

