//
// OryUpdateRecoveryFlowBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Update Recovery Flow Request Body */
public enum OryUpdateRecoveryFlowBody: Sendable, Codable, ParameterConvertible, Hashable {
    case typeOryUpdateRecoveryFlowWithCodeMethod(OryUpdateRecoveryFlowWithCodeMethod)
    case typeOryUpdateRecoveryFlowWithLinkMethod(OryUpdateRecoveryFlowWithLinkMethod)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeOryUpdateRecoveryFlowWithCodeMethod(let value):
            try container.encode(value)
        case .typeOryUpdateRecoveryFlowWithLinkMethod(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(OryUpdateRecoveryFlowWithCodeMethod.self) {
            self = .typeOryUpdateRecoveryFlowWithCodeMethod(value)
        } else if let value = try? container.decode(OryUpdateRecoveryFlowWithLinkMethod.self) {
            self = .typeOryUpdateRecoveryFlowWithLinkMethod(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of OryUpdateRecoveryFlowBody"))
        }
    }
}

