//
// OryUiNodeTextAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OryUiNodeTextAttributes: Sendable, Codable, ParameterConvertible, Hashable {

    public enum OryNodeType: String, Sendable, Codable, CaseIterable {
        case text = "text"
        case input = "input"
        case img = "img"
        case a = "a"
        case script = "script"
    }
    /** A unique identifier */
    public var id: String
    /** NodeType represents this node's types. It is a mirror of `node.type` and is primarily used to allow compatibility with OpenAPI 3.0.  In this struct it technically always is \"text\". text Text input Input img Image a Anchor script Script */
    public var nodeType: OryNodeType
    public var text: OryUiText

    public init(id: String, nodeType: OryNodeType, text: OryUiText) {
        self.id = id
        self.nodeType = nodeType
        self.text = text
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case nodeType = "node_type"
        case text
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(nodeType, forKey: .nodeType)
        try container.encode(text, forKey: .text)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension OryUiNodeTextAttributes: Identifiable {}
