//
// OryUiNodeAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum OryUiNodeAttributes: Sendable, Codable, ParameterConvertible, Hashable {
    case typeOryUiNodeAnchorAttributes(OryUiNodeAnchorAttributes)
    case typeOryUiNodeImageAttributes(OryUiNodeImageAttributes)
    case typeOryUiNodeInputAttributes(OryUiNodeInputAttributes)
    case typeOryUiNodeScriptAttributes(OryUiNodeScriptAttributes)
    case typeOryUiNodeTextAttributes(OryUiNodeTextAttributes)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeOryUiNodeAnchorAttributes(let value):
            try container.encode(value)
        case .typeOryUiNodeImageAttributes(let value):
            try container.encode(value)
        case .typeOryUiNodeInputAttributes(let value):
            try container.encode(value)
        case .typeOryUiNodeScriptAttributes(let value):
            try container.encode(value)
        case .typeOryUiNodeTextAttributes(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(OryUiNodeAnchorAttributes.self) {
            self = .typeOryUiNodeAnchorAttributes(value)
        } else if let value = try? container.decode(OryUiNodeImageAttributes.self) {
            self = .typeOryUiNodeImageAttributes(value)
        } else if let value = try? container.decode(OryUiNodeInputAttributes.self) {
            self = .typeOryUiNodeInputAttributes(value)
        } else if let value = try? container.decode(OryUiNodeScriptAttributes.self) {
            self = .typeOryUiNodeScriptAttributes(value)
        } else if let value = try? container.decode(OryUiNodeTextAttributes.self) {
            self = .typeOryUiNodeTextAttributes(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of OryUiNodeAttributes"))
        }
    }
}
