//
// OryUpdateVerificationFlowBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Update Verification Flow Request Body */
public enum OryUpdateVerificationFlowBody: Sendable, Codable, ParameterConvertible, Hashable {
    case typeOryUpdateVerificationFlowWithCodeMethod(OryUpdateVerificationFlowWithCodeMethod)
    case typeOryUpdateVerificationFlowWithLinkMethod(OryUpdateVerificationFlowWithLinkMethod)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeOryUpdateVerificationFlowWithCodeMethod(let value):
            try container.encode(value)
        case .typeOryUpdateVerificationFlowWithLinkMethod(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(OryUpdateVerificationFlowWithCodeMethod.self) {
            self = .typeOryUpdateVerificationFlowWithCodeMethod(value)
        } else if let value = try? container.decode(OryUpdateVerificationFlowWithLinkMethod.self) {
            self = .typeOryUpdateVerificationFlowWithLinkMethod(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of OryUpdateVerificationFlowBody"))
        }
    }
}

