//
// OryUiNodeMeta.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** This might include a label and other information that can optionally be used to render UIs. */
public struct OryUiNodeMeta: Sendable, Codable, ParameterConvertible, Hashable {

    public var label: OryUiText?

    public init(label: OryUiText? = nil) {
        self.label = label
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case label
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(label, forKey: .label)
    }
}

