//
// OryUpdateIdentityBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Update Identity Body */
public struct OryUpdateIdentityBody: Sendable, Codable, ParameterConvertible, Hashable {

    public enum OryState: String, Sendable, Codable, CaseIterable {
        case active = "active"
        case inactive = "inactive"
    }
    public var credentials: OryIdentityWithCredentials?
    /** Store metadata about the user which is only accessible through admin APIs such as `GET /admin/identities/<id>`. */
    public var metadataAdmin: JSONValue?
    /** Store metadata about the identity which the identity itself can see when calling for example the session endpoint. Do not store sensitive information (e.g. credit score) about the identity in this field. */
    public var metadataPublic: JSONValue?
    /** SchemaID is the ID of the JSON Schema to be used for validating the identity's traits. If set will update the Identity's SchemaID. */
    public var schemaId: String
    /** State is the identity's state. active StateActive inactive StateInactive */
    public var state: OryState
    /** Traits represent an identity's traits. The identity is able to create, modify, and delete traits in a self-service manner. The input will always be validated against the JSON Schema defined in `schema_id`. */
    public var traits: JSONValue

    public init(credentials: OryIdentityWithCredentials? = nil, metadataAdmin: JSONValue? = nil, metadataPublic: JSONValue? = nil, schemaId: String, state: OryState, traits: JSONValue) {
        self.credentials = credentials
        self.metadataAdmin = metadataAdmin
        self.metadataPublic = metadataPublic
        self.schemaId = schemaId
        self.state = state
        self.traits = traits
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case credentials
        case metadataAdmin = "metadata_admin"
        case metadataPublic = "metadata_public"
        case schemaId = "schema_id"
        case state
        case traits
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(credentials, forKey: .credentials)
        try container.encodeIfPresent(metadataAdmin, forKey: .metadataAdmin)
        try container.encodeIfPresent(metadataPublic, forKey: .metadataPublic)
        try container.encode(schemaId, forKey: .schemaId)
        try container.encode(state, forKey: .state)
        try container.encode(traits, forKey: .traits)
    }
}

