//
// OryUiNodeAnchorAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OryUiNodeAnchorAttributes: Sendable, Codable, ParameterConvertible, Hashable {

    public enum OryNodeType: String, Sendable, Codable, CaseIterable {
        case text = "text"
        case input = "input"
        case img = "img"
        case a = "a"
        case script = "script"
    }
    /** The link's href (destination) URL.  format: uri */
    public var href: String
    /** A unique identifier */
    public var id: String
    /** NodeType represents this node's types. It is a mirror of `node.type` and is primarily used to allow compatibility with OpenAPI 3.0.  In this struct it technically always is \"a\". text Text input Input img Image a Anchor script Script */
    public var nodeType: OryNodeType
    public var title: OryUiText

    public init(href: String, id: String, nodeType: OryNodeType, title: OryUiText) {
        self.href = href
        self.id = id
        self.nodeType = nodeType
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case href
        case id
        case nodeType = "node_type"
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(href, forKey: .href)
        try container.encode(id, forKey: .id)
        try container.encode(nodeType, forKey: .nodeType)
        try container.encode(title, forKey: .title)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension OryUiNodeAnchorAttributes: Identifiable {}
