//
// ContinueWith.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ContinueWith: Codable, JSONEncodable, Hashable {
    case typeContinueWithSetOrySessionToken(ContinueWithSetOrySessionToken)
    case typeContinueWithVerificationUi(ContinueWithVerificationUi)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeContinueWithSetOrySessionToken(let value):
            try container.encode(value)
        case .typeContinueWithVerificationUi(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(ContinueWithSetOrySessionToken.self) {
            self = .typeContinueWithSetOrySessionToken(value)
        } else if let value = try? container.decode(ContinueWithVerificationUi.self) {
            self = .typeContinueWithVerificationUi(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of ContinueWith"))
        }
    }
}

