//
// IdentityPatchResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Response for a single identity patch */
public struct IdentityPatchResponse: Codable, JSONEncodable, Hashable {

    public enum Action: String, Codable, CaseIterable {
        case create = "create"
    }
    /** The action for this specific patch create ActionCreate  Create this identity. */
    public var action: Action?
    /** The identity ID payload of this patch */
    public var identity: String?
    /** The ID of this patch response, if an ID was specified in the patch. */
    public var patchId: String?

    public init(action: Action? = nil, identity: String? = nil, patchId: String? = nil) {
        self.action = action
        self.identity = identity
        self.patchId = patchId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case action
        case identity
        case patchId = "patch_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(action, forKey: .action)
        try container.encodeIfPresent(identity, forKey: .identity)
        try container.encodeIfPresent(patchId, forKey: .patchId)
    }
}

