//
// UpdateSettingsFlowWithOidcMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** nolint:deadcode,unused */
public struct UpdateSettingsFlowWithOidcMethod: Codable, JSONEncodable, Hashable {

    /** Flow ID is the flow's ID.  in: query */
    public var flow: String?
    /** Link this provider  Either this or `unlink` must be set.  type: string in: body */
    public var link: String?
    /** Method  Should be set to profile when trying to update a profile. */
    public var method: String
    /** The identity's traits  in: body */
    public var traits: AnyCodable?
    /** Unlink this provider  Either this or `link` must be set.  type: string in: body */
    public var unlink: String?

    public init(flow: String? = nil, link: String? = nil, method: String, traits: AnyCodable? = nil, unlink: String? = nil) {
        self.flow = flow
        self.link = link
        self.method = method
        self.traits = traits
        self.unlink = unlink
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case flow
        case link
        case method
        case traits
        case unlink
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(flow, forKey: .flow)
        try container.encodeIfPresent(link, forKey: .link)
        try container.encode(method, forKey: .method)
        try container.encodeIfPresent(traits, forKey: .traits)
        try container.encodeIfPresent(unlink, forKey: .unlink)
    }
}

