//
// CourierAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class CourierAPI {

    /**
     List Messages
     
     - parameter perPage: (query) Items per Page  This is the number of items per page. (optional, default to 250)
     - parameter page: (query) Pagination Page  This value is currently an integer, but it is not sequential. The value is not the page number, but a reference. The next page can be any number and some numbers might return an empty list.  For example, page 2 might not follow after page 1. And even if page 3 and 5 exist, but page 4 might not exist. (optional, default to 1)
     - parameter status: (query) Status filters out messages based on status. If no value is provided, it doesn&#39;t take effect on filter. (optional)
     - parameter recipient: (query) Recipient filters out messages based on recipient. If no value is provided, it doesn&#39;t take effect on filter. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listCourierMessages(perPage: Int64? = nil, page: Int64? = nil, status: CourierMessageStatus? = nil, recipient: String? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: [Message]?, _ error: Error?) -> Void)) -> RequestTask {
        return listCourierMessagesWithRequestBuilder(perPage: perPage, page: page, status: status, recipient: recipient).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List Messages
     - GET /admin/courier/messages
     - Lists all messages by given status and recipient.
     - API Key:
       - type: apiKey Authorization 
       - name: oryAccessToken
     - parameter perPage: (query) Items per Page  This is the number of items per page. (optional, default to 250)
     - parameter page: (query) Pagination Page  This value is currently an integer, but it is not sequential. The value is not the page number, but a reference. The next page can be any number and some numbers might return an empty list.  For example, page 2 might not follow after page 1. And even if page 3 and 5 exist, but page 4 might not exist. (optional, default to 1)
     - parameter status: (query) Status filters out messages based on status. If no value is provided, it doesn&#39;t take effect on filter. (optional)
     - parameter recipient: (query) Recipient filters out messages based on recipient. If no value is provided, it doesn&#39;t take effect on filter. (optional)
     - returns: RequestBuilder<[Message]> 
     */
    open class func listCourierMessagesWithRequestBuilder(perPage: Int64? = nil, page: Int64? = nil, status: CourierMessageStatus? = nil, recipient: String? = nil) -> RequestBuilder<[Message]> {
        let localVariablePath = "/admin/courier/messages"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "per_page": (wrappedValue: perPage?.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "status": (wrappedValue: status?.encodeToJSON(), isExplode: true),
            "recipient": (wrappedValue: recipient?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Message]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
